baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Upbound Docs"
theme = "upbound"
enableGitInfo = true
uglyurls = false
timeout = 180000

disableKinds = ["taxonomy", "term", "RSS"]

[build]
  # writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.tableOfContents]
      startLevel = 1
      endLevel = 9
    [markup.goldmark.highlight]
      codeFences = true
      noClasses = false
      linenos = false
      anchorLineNos = true
      lineNumbersInTable = false

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "assets/content"
    includeFiles = ["**/**.png", "**/**.jpg", "**/**.jpeg", "**/**.gif"]

[security]
  [security.funcs]
    getenv = ["^CONTEXT", "^REVIEW_ID"]

[params]
  repoLink = "https://github.com/upbound/"
  anchors = { min = 2, max = 5 }
  description = "Crossplane lets you build a control plane with Kubernetes-style declarative and API-driven configuration and management for anything."

[Taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Concepts"
  weight = 1
  identifier = "concepts"
  url = "/concepts/"

[[menu.main]]
  name = "Contribute"
  weight = 2
  identifier = "contribute"
  url = "/contribute/"

[[menu.main]]
  name = "Knowledge Base"
  weight = 3
  identifier = "knowledge-base"
  url = "/knowledge-base/"

[[menu.main]]
  name = "Providers"
  weight = 4
  identifier = "providers"
  url = "/providers/"

[[menu.main]]
  name = "Quickstart"
  weight = 5
  identifier = "quickstart"
  url = "/quickstart/"

[[menu.main]]
  name = "Reference"
  weight = 6
  identifier = "reference"
  url = "/reference/"

[[menu.main]]
  name = "Spaces"
  weight = 7
  identifier = "spaces"
  url = "/spaces/"

[[menu.main]]
  name = "Support"
  weight = 8
  identifier = "support"
  url = "/support/"

[[menu.main]]
  name = "Upbound Marketplace"
  weight = 9
  identifier = "upbound-marketplace"
  url = "/upbound-marketplace/"

[[menu.main]]
  name = "UXP"
  weight = 10
  identifier = "uxp"
  url = "/uxp/"

[[menu.main]]
  name = "XP Arch Framework"
  weight = 11
  identifier = "xp-arch-framework"
  url = "/xp-arch-framework/"
